### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by izinezion** [izinezion/CometEmulator-MHN#1]
- [x] Sistema de restrição de rank ao comprar LTD.
- [x] Restringir ganho de diamantes por hora para Staffs.
- [ ] Alterar BAN para Prisão (Usuário ficará restringido e mudo em um quarto especificado).
